services:
  api:
    image: node:22
    working_dir: /app
    command: sh -c "npm install && npm run dev:api"
    environment:
      API_PORT: 3000
      DATABASE_URL: postgres://aboba:aboba@postgres:5432/aboba?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3001:3000'
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: aboba
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  workers:
    image: node:22
    working_dir: /app
    command: sh -c "npm install && npm run dev:workers"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - ./:/app

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Console
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:


